/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka.producer;

import java.util.Objects;
import java.util.Properties;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;
import org.apache.kafka.common.serialization.StringSerializer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
public class ProducerUtils {
    public static final Logger log = LoggerFactory.getLogger(ProducerUtils.class.getSimpleName());

    public static Properties defaultProducerProperties() {
        Properties producerProps = new Properties();
        producerProps.setProperty("bootstrap.servers", "localhost:9092");
        producerProps.setProperty("key.serializer", StringSerializer.class.getName());
        producerProps.setProperty("value.serializer", StringSerializer.class.getName());
        return producerProps;
    }
    public static void logSendCallback(RecordMetadata metadata, Exception exception) {
        if(Objects.isNull(exception)) {
            log.info("Topic : {}", metadata.topic());
            log.info("Partition : {}", metadata.partition());
            log.info("OffSet : {}", metadata.offset());
            log.info("Key : {}", metadata.serializedKeySize());
            log.info("Value : {}", metadata.serializedValueSize());
        } else {
            log.error("Failed to send ", exception);
        }
    }

}
